#!/bin/bash
#postinst script for chromeos

set -x

. /usr/share/debconf/confmodule

case "$1" in
  configure|reconfigure)
    rm -rf /opt/chromeos
    LKGR=$(curl http://chromium-status.appspot.com/lkgr)
    URL="http://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_ChromiumOS/${LKGR}/chrome-linux.zip"
    ZIPFILE="/tmp/chromeos-linux.zip"

    zip -T $ZIPFILE
    # ABORTS IF ZIP FILES ARE NO GOOD.
    if [ $? != "0" ] ; then
      rm $ZIPFILE
    fi

    curl -z $ZIPFILE -o $ZIPFILE -L "$URL"
    unzip $ZIPFILE -d "/opt/"
    mv /opt/chrome-linux /opt/chromeos
    chmod 775 /opt/chromeos -R
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    
  ;;

  *)
       echo "postinst called with unknown argument \`$1'" >&2
       exit 1
  ;;
esac

#DEBHELPER#

exit 0