#!/bin/bash
#postinst script for chromeos

set -x

. /usr/share/debconf/confmodule

case "$1" in
  purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    rm -rf /opt/chromeos
  ;;
  *)
       echo "postinst called with unknown argument \`$1'" >&2
       exit 1
  ;;
esac

#DEBHELPER#

exit 0