#!/bin/bash
#postinst script for chromeos

set -x

. /usr/share/debconf/confmodule

case "$1" in
  configure|reconfigure)
    rm -rf /opt/chromeos
    VERSION=$(curl http://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_ChromiumOS/LAST_CHANGE)
    URL="http://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_ChromiumOS/${VERSION}/chrome-linux.zip"
    curl -z "/tmp/chromeos-linux.zip" -o "/tmp/chromeos-linux.zip" -L "$URL"
    unzip "/tmp/chromeos-linux.zip" -d "/opt/"
    mv /opt/chrome-linux /opt/chromeos
    chmod 775 /opt/chromeos -R
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    
  ;;

  *)
       echo "postinst called with unknown argument \`$1'" >&2
       exit 1
  ;;
esac

#DEBHELPER#

exit 0